# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VK8V5gf53LCo55XvECw2RRXnZwU_Gtzj
"""

import pandas as pd
baza={
    "FISH":[ "Sotvildiyev Javoxir" , "Akbarova Nigina " , "Tursinboyev Omadjon", "Begaliyeva Nigora", "Yoqubov Umidjon", "Orifjonova Zilola", "Shumqorov Fazlidin", "Gulomova Ruxshona", "Tursinboyev Latipjon", "Nomonova Umida" ],
    "yoshi":[  "16" ,"13","14","13","10", "9", "16","8",'17' ,"13" ],
    "maktabi":[  "31-maktab" ,"32-maktab" ,"33-maktab","32-maktab","36-maktab","49-maktab","31-maktab","30-maktab","39-maktab","31-maktab" ],
    "jinsi":[  "o'g'il bola " , "qiz bola" ,"o'g'il bola ","qiz bola" ,"o'g'il bola ","qiz bola" ,"o'g'il bola ","qiz bola", "o'g'il bola ","qiz bola" ],
    "Manzili":[  "Andijon shahar", "andijon tuman" ,  "Andijon shahar", "Andijon shahar", "Andijon shahar", "Andijon shahar", "Andijon shahar", "Andijon shahar", "Andijon shahar", "Andijon shahar" ]
}
db=pd.DataFrame(baza)
print(db)

filtr=db[db['jinsi']=="o'g'il bola "]
print(filtr)

filtr=db[(db['jinsi']=="o'g'il bola ") &  (db["yoshi"]>"15")]
print(filtr)